# -*- coding: utf-8 -*-
"""L4-student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wr4IB1ZMy9osGG2ef0BpXKF2ZqDKQovz

## Lab 4 - Cross-encoder re-ranking
"""

!pip install langchain-text-splitters
!pip install chromadb
!pip install sentence_transformers
import chromadb
from langchain_text_splitters import RecursiveCharacterTextSplitter, SentenceTransformersTokenTextSplitter

def load_chroma(filename, collection_name, embedding_function):

    # Read PDF
    reader = PdfReader(filename)
    pdf_texts = [page.extract_text().strip() for page in reader.pages]

    # Remove empty pages
    pdf_texts = [text for text in pdf_texts if text]

    # Character splitting
    character_splitter = RecursiveCharacterTextSplitter(
        separators=["\n\n", "\n", ". ", " ", ""],
        chunk_size=1000,
        chunk_overlap=0
    )

    character_split_texts = character_splitter.split_text(
        "\n\n".join(pdf_texts)
    )

    # Token splitting
    token_splitter = SentenceTransformersTokenTextSplitter(
        chunk_overlap=0,
        tokens_per_chunk=256
    )

    token_split_texts = []

    for text in character_split_texts:
        token_split_texts.extend(
            token_splitter.split_text(text)
        )

    # Create Chroma collection
    chroma_client = chromadb.Client()

    try:
        chroma_client.delete_collection(collection_name)
        print(f"Deleted existing collection: {collection_name}")
    except:
        pass

    collection = chroma_client.create_collection(
        name=collection_name,
        embedding_function=embedding_function
    )

    # Add documents
    ids = [str(i) for i in range(len(token_split_texts))]

    collection.add(
        ids=ids,
        documents=token_split_texts
    )

    return collection

import textwrap

def word_wrap(text, width=80):
    return textwrap.fill(text, width=width)

import numpy as np
from tqdm import tqdm

def project_embeddings(embeddings, umap_transform):
    """
    Project high-dimensional embeddings into 2D using a trained UMAP model.
    """
    umap_embeddings = np.empty((len(embeddings), 2))

    for i, embedding in enumerate(tqdm(embeddings)):
        umap_embeddings[i] = umap_transform.transform([embedding])

    return umap_embeddings

from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
import numpy as np

!pip install pypdf
from pypdf import PdfReader

embedding_function = SentenceTransformerEmbeddingFunction()

chroma_collection = load_chroma(filename='sample_data/2025_AnnualReport.pdf', collection_name='2025_AnnualReport', embedding_function=embedding_function)
chroma_collection.count()

"""# Re-ranking the long tail"""

query = "What has been the investment in research and development?"
results = chroma_collection.query(query_texts=query, n_results=10, include=['documents', 'embeddings'])

retrieved_documents = results['documents'][0]

for document in results['documents'][0]:
    print(word_wrap(document))
    print('')

from sentence_transformers import CrossEncoder
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

pairs = [[query, doc] for doc in retrieved_documents]
scores = cross_encoder.predict(pairs)
print("Scores:")
for score in scores:
    print(score)

print("New Ordering:")
for o in np.argsort(scores)[::-1]:
    print(o+1)

"""# Re-ranking with Query Expansion"""

original_query = "What were the most important factors that contributed to increases in revenue?"
generated_queries = [
    "What were the major drivers of revenue growth?",
    "Were there any new product launches that contributed to the increase in revenue?",
    "Did any changes in pricing or promotions impact the revenue growth?",
    "What were the key market trends that facilitated the increase in revenue?",
    "Did any acquisitions or partnerships contribute to the revenue growth?"
]

queries = [original_query] + generated_queries

results = chroma_collection.query(query_texts=queries, n_results=10, include=['documents', 'embeddings'])
retrieved_documents = results['documents']

# Deduplicate the retrieved documents
unique_documents = set()
for documents in retrieved_documents:
    for document in documents:
        unique_documents.add(document)

unique_documents = list(unique_documents)

pairs = []
for doc in unique_documents:
    pairs.append([original_query, doc])

scores = cross_encoder.predict(pairs)

print("Scores:")
for score in scores:
    print(score)

print("New Ordering:")
for o in np.argsort(scores)[::-1]:
    print(o)







































































